Repository JevsJevs/SoftwareEngineering-MC656-2024-1s, pull requests merged in 2024-06, with the labels that each got.

#46 #40 refactor: removing last olympics web scraper
  backend/scrapping/List_of_IOC_country_codes_1.csv
  backend/scrapping/aggregate.py
  backend/scrapping/esportes.csv
  backend/scrapping/esportes_en.csv
  backend/scrapping/eventos.csv
  backend/scrapping/eventos2.csv
  backend/scrapping/eventos_en.csv
  backend/scrapping/get_events.py
  backend/scrapping/get_sports.py
  backend/scrapping/kaggle/athletes.csv
  backend/scrapping/kaggle/fonte.txt
  backend/scrapping/kaggle/license
  backend/scrapping/kaggle/medals.csv
  backend/scrapping/noc_pt.csv
  backend/scrapping/pt/world.sql
  backend/scrapping/temp.py
  backend/scrapping/temp.txt
  backend/scrapping/utils.py
  backend/scrapping/world.sql
Labels: A4

#48 41 refactor repeating db connection clamping at backend main
  backend/database/DBConnector.py
  backend/database/__init__.py
  backend/main.py
Labels: AvaliacaoA4, A4

#45 #38 epic/refactor code smells
  .gitignore
  backend/database/DBConnector.py
  backend/database/__init__.py
  backend/main.py
  backend/models.py
  backend/scrapping/List_of_IOC_country_codes_1.csv
  backend/scrapping/aggregate.py
  backend/scrapping/esportes.csv
  backend/scrapping/esportes_en.csv
  backend/scrapping/eventos.csv
  backend/scrapping/eventos2.csv
  backend/scrapping/eventos_en.csv
  backend/scrapping/get_events.py
  backend/scrapping/get_sports.py
  backend/scrapping/kaggle/athletes.csv
  backend/scrapping/kaggle/fonte.txt
  backend/scrapping/kaggle/license
  backend/scrapping/kaggle/medals.csv
  backend/scrapping/noc_pt.csv
  backend/scrapping/pt/world.sql
  backend/scrapping/temp.py
  backend/scrapping/temp.txt
  backend/scrapping/utils.py
  backend/scrapping/world.sql
  backend/tests/__init__.py
  backend/tests/test_main.py
  frontend/src/components/newsCard/newsCard.js
  frontend/src/components/newsModal/newsModal.js
  frontend/src/pages/news.js
  frontend/src/pages/table.js
Labels: AvaliacaoA4, A4

#58 55 break tests in single scenarios
  .gitignore
  backend/main.py
  backend/makefile
  backend/tests/test_all_medal.py
  backend/tests/test_main.py
  backend/tests/test_medal_by_category.py
  backend/tests/test_medal_by_country.py
  backend/tests/test_medal_ratio.py
  backend/tests/test_medal_top.py
Labels: A5
